env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-essential
  - airbnb-base
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - import
  - prettier
rules: { 'vue/multi-word-component-names': off, 'prettier/prettier': 'error' }
globals:
  twttr: readonly
settings:
  import/resolver:
    alias: { map: [['@', './src']] }
