env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-essential
  - airbnb-base
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules: { 'vue/multi-word-component-names': off }
globals:
  twttr: readonly
